"""empty message

Revision ID: 04ff8e8a76c7
Revises: d63b8d8511ef
Create Date: 2023-11-13 18:20:00.350558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04ff8e8a76c7'
down_revision = 'd63b8d8511ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defective_lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lane_number', sa.Integer(), nullable=True),
    sa.Column('is_defective', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lane_number')
    )
    op.drop_table('DefectiveLane')
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('lanes',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('lanes',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    op.create_table('DefectiveLane',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lane_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_defective', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('defective_lane')
    # ### end Alembic commands ###
