"""Initial migration

Revision ID: 52cd8ca5066a
Revises: 
Create Date: 2023-11-26 15:33:05.876553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cd8ca5066a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defective_lane',
    sa.Column('lane_number', sa.Integer(), nullable=False),
    sa.Column('is_defective', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('lane_number'),
    sa.UniqueConstraint('lane_number')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('players', sa.Integer(), nullable=True),
    sa.Column('kids', sa.Boolean(), nullable=True),
    sa.Column('lanes', sa.String(length=100), nullable=True),
    sa.Column('specialevent', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('defective_lane')
    # ### end Alembic commands ###
